#!/usr/bin/env python3
"""Assemble the standalone app from the skill's modules.

    python3 app/build_app.py [-o netmon-app.py]

Produces one self-contained file that needs no installation and no packages.
Keeping the sources separate and inlining at build time means the app and the
skill's CLI never drift apart -- there is one implementation, not two.
"""

from __future__ import annotations

import argparse
import ast

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPTS = HERE.parent / "scripts"

HEADER = '''#!/usr/bin/env python3
"""Switch Monitor -- standalone SNMP monitoring for network switches.

Run it with no arguments to open the dashboard in your browser:

    python3 netmon-app.py

Run it with a command to use the command line instead:

    python3 netmon-app.py check 192.168.1.254 -c public
    python3 netmon-app.py report --out dashboard.html

Everything is the Python standard library. There is nothing to install.
SNMPv3 encryption (authPriv) optionally uses the 'cryptography' package;
SNMPv3 authentication and all of v1/v2c need no packages at all.

This file is generated by app/build_app.py -- edit the sources, not this.
"""

from __future__ import annotations

'''


# Every source module's own `if __name__ == "__main__"` block is stripped
# during concatenation, so the built file needs exactly one entry point of
# its own -- without this it would run and silently do nothing.
FOOTER = '''

# ==========================================================================
# Entry point
# ==========================================================================

if __name__ == "__main__":
    sys.exit(main_dispatch())
'''

INLINED_MODULES = {"snmp", "netmon"}


def _should_drop(node: ast.stmt, index: int) -> bool:
    """Decide whether a top-level statement survives concatenation."""
    # The module docstring -- the combined file supplies its own.
    if (index == 0 and isinstance(node, ast.Expr)
            and isinstance(node.value, ast.Constant)
            and isinstance(node.value.value, str)):
        return True
    # `from __future__` is only legal once, at the very top.
    if isinstance(node, ast.ImportFrom) and node.module == "__future__":
        return True
    # Cross-module imports are meaningless once everything is one file.
    if isinstance(node, ast.ImportFrom) and node.module in INLINED_MODULES:
        return True
    if isinstance(node, ast.Import):
        if all(alias.name in INLINED_MODULES for alias in node.names):
            return True
    # `sys.path.insert(...)` only existed to find the sibling modules.
    if (isinstance(node, ast.Expr) and isinstance(node.value, ast.Call)
            and isinstance(node.value.func, ast.Attribute)
            and node.value.func.attr == "insert"
            and ast.unparse(node.value.func).startswith("sys.path")):
        return True
    # Each source has its own entry point; the built file supplies one.
    if isinstance(node, ast.If) and ast.unparse(node.test).startswith(
        "__name__ =="
    ):
        return True
    # __all__ would hide names the later sections rely on.
    if isinstance(node, ast.Assign) and any(
        isinstance(t, ast.Name) and t.id == "__all__" for t in node.targets
    ):
        return True
    return False


def strip_module(path: Path, drop_names: set[str] = frozenset()) -> str:
    """Return a module's body, minus the parts that cannot be concatenated.

    Works from the parse tree rather than line matching, so multi-line
    statements (an `__all__` list, a long import) are removed in full.
    """
    text = path.read_text()
    lines = text.splitlines()
    tree = ast.parse(text)

    drop: set[int] = set()
    for index, node in enumerate(tree.body):
        named = isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
        if _should_drop(node, index) or (named and node.name in drop_names):
            # Include any decorator lines above the statement.
            start = min(
                [node.lineno] + [d.lineno for d in getattr(node, "decorator_list", [])]
            )
            drop.update(range(start, (node.end_lineno or node.lineno) + 1))

    kept = [line for n, line in enumerate(lines, 1) if n not in drop]
    return "\n".join(kept).strip("\n")


def build(output: Path) -> Path:
    parts = [HEADER]
    for name, source in (
        ("SNMP engine", SCRIPTS / "snmp.py"),
        ("Polling, storage and alerting", SCRIPTS / "netmon.py"),
        ("Built-in switch simulator", SCRIPTS / "mock_switch.py"),
        ("Web application", HERE / "app_main.py"),
    ):
        if not source.exists():
            raise SystemExit(f"missing source file: {source}")
        parts.append(
            f"# {'=' * 74}\n# {name}  (from {source.name})\n# {'=' * 74}\n"
        )
        # mock_switch defines its own main(); keeping it would shadow the CLI
        # entry point that netmon.py provides.
        drop = {"main"} if source.name == "mock_switch.py" else frozenset()
        parts.append(strip_module(source, drop))
        parts.append("\n")

    text = "\n".join(parts).rstrip() + "\n" + FOOTER

    # Fail loudly rather than shipping a file that will not import.
    try:
        compile(text, str(output), "exec")
    except SyntaxError as exc:
        raise SystemExit(f"generated file has a syntax error at line {exc.lineno}: {exc.msg}")

    # A file that compiles but has no entry point runs and does nothing --
    # the exact failure this footer exists to prevent. Check it explicitly.
    tree = ast.parse(text)
    entry = [
        node for node in tree.body
        if isinstance(node, ast.If) and ast.unparse(node.test).startswith("__name__ ==")
    ]
    if len(entry) != 1:
        raise SystemExit(
            f"generated file has {len(entry)} entry points, expected exactly 1"
        )
    for required in ("main_dispatch", "run_app", "poll_device", "Session",
                     "MockSwitch", "serve", "main"):
        if not any(
            isinstance(n, (ast.FunctionDef, ast.ClassDef)) and n.name == required
            for n in tree.body
        ):
            raise SystemExit(f"generated file is missing {required}()")

    output.write_text(text)
    output.chmod(0o755)
    return output


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--out", default=str(HERE.parent / "netmon-app.py"))
    args = ap.parse_args()
    out = build(Path(args.out))
    size = out.stat().st_size
    lines = len(out.read_text().splitlines())
    print(f"built {out} ({size // 1024} KB, {lines} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
